import Footer from '@/components/ui/Footer'
import MainNavigation from '@/components/ui/MainNavigation'
import {cormorant, manrope, poppins} from '@/styles/font'
import {Theme, ThemePanel} from '@radix-ui/themes'
import '@radix-ui/themes/styles.css'
import type {Metadata} from 'next'
import 'next-cloudinary/dist/cld-video-player.css'
import React, {PropsWithChildren} from 'react'
import './globals.css'

export const metadata: Metadata = {
   title: 'Prod203 | ',
   description: 'Generated by create next app',
}

export async function generateStaticParams() {
   return [{lang: 'en-US'}, {lang: 'fr-FR'}]
}

interface LayoutProps extends PropsWithChildren {
   params: {
      lang: string
   }
}

function RootLayout({children, params}: LayoutProps) {
   return (
      <html
         lang={params.lang}
         data-theme={'customTheme'}>
         <body
            className={`${cormorant.variable} ${manrope.variable} ${poppins.variable} font-poppins font-extralight`}>
            <Theme
               appearance="dark"
               accentColor="gray"
               grayColor={'gray'}
               className={'bg-base-100'}
               panelBackground={'translucent'}
               radius="medium"
               scaling="95%">
               {/*<ThemePanel />*/}
               <MainNavigation />
               {children}
               <Footer />
            </Theme>
         </body>
      </html>
   )
}

export default RootLayout
