import Footer from '@/components/Footer'
import NavBar from '@/components/navigationFeature/NavBar'
import {cormorant, manrope, poppins} from '@/styles/font'
import type {Metadata} from 'next'
import React, {PropsWithChildren} from 'react'
import './globals.css'

export const metadata: Metadata = {
   title: 'Prod203 | ',
   description: 'Generated by create next app',
}

export async function generateStaticParams() {
   return [{lang: 'en-US'}, {lang: 'fr-FR'}]
}

function RootLayout({children, params}: PropsWithChildren<{params: {lang: string}}>) {
   return (
      <html
         lang={params.lang}
         data-theme={'customTheme'}>
         <body
            className={`${cormorant.variable} ${manrope.variable} ${poppins.variable} font-poppins font-extralight`}>
            <NavBar />
            {children}
            <Footer />
         </body>
      </html>
   )
}

export default RootLayout
