import Project from '@/schemas/project.schema'

export const mockedCategories = [
   {
      name: 'concert',
      slug: {_type: 'slug', current: 'concert'},
      _createdAt: new Date('2023-02-14T15:58:35.017893'),
      _updatedAt: new Date('2023-06-10T15:58:35.017914'),
      _id: 'category_1',
      _rev: 'rev_1',
      _type: 'category',
   },
   {
      name: 'live-event',
      slug: {_type: 'slug', current: 'live-event'},
      _createdAt: new Date('2023-03-29T15:58:35.017922'),
      _updatedAt: new Date('2023-06-04T15:58:35.017926'),
      _id: 'category_2',
      _rev: 'rev_2',
      _type: 'category',
   },
   {
      name: 'Original Soundtrack',
      slug: {_type: 'slug', current: 'original-soundtrack'},
      _createdAt: new Date('2023-03-06T15:58:35.017932'),
      _updatedAt: new Date('2023-07-08T15:58:35.017937'),
      _id: 'category_3',
      _rev: 'rev_3',
      _type: 'category',
   },
   {
      name: 'Music Video',
      slug: {_type: 'slug', current: 'music-video'},
      _createdAt: new Date('2023-02-01T15:58:35.017942'),
      _updatedAt: new Date('2023-06-20T15:58:35.017945'),
      _id: 'category_4',
      _rev: 'rev_4',
      _type: 'category',
   },
   {
      name: 'Commercial',
      slug: {_type: 'slug', current: 'commercial'},
      _createdAt: new Date('2023-03-20T15:58:35.017950'),
      _updatedAt: new Date('2023-06-20T15:58:35.017954'),
      _id: 'category_5',
      _rev: 'rev_5',
      _type: 'category',
   },
   {
      name: 'Restauration',
      slug: {_type: 'slug', current: 'restauration'},
      _createdAt: new Date('2023-01-20T15:58:35.017959'),
      _updatedAt: new Date('2023-06-25T15:58:35.017963'),
      _id: 'category_6',
      _rev: 'rev_6',
      _type: 'category',
   },
]

export const mockedProjects: Project[] = [
   {
      title: 'Project Title 1',
      slug: {current: 'project-title-1', _type: 'slug'},
      thumbnail: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      releaseDate: new Date(new Date('2023-08-19T16:00:23.907295')),
      description: [
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_749',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_3318',
                  _type: 'span',
                  marks: [],
                  text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
               },
            ],
         },
      ],
      preview: {
         _type: 'file',
         asset: {
            _ref: 'https://player.vimeo.com/external/269971860.hd.mp4?s=eae965838585cc8342bb5d5253d06a52b2415570&profile_id=174&oauth2_token_id=57447761',
            _type: 'reference',
         },
      },
      client: {_ref: 'client_ref_10', _type: 'reference'},
      _createdAt: new Date('2023-08-19T16:00:23.907295'),
      _updatedAt: new Date('2023-08-12T16:00:23.907300'),
      _id: 'project_1',
      _rev: 'project_rev_1',
      _type: 'project',
      category: {_ref: 'category_5', _type: 'reference'},
   },
   {
      title: 'Project Title 2',
      slug: {current: 'project-title-2', _type: 'slug'},
      thumbnail: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      releaseDate: new Date('2023-05-23T16:00:23.907308'),
      description: [
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_9539',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_697',
                  _type: 'span',
                  marks: [],
                  text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
               },
            ],
         },
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_5955',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_3480',
                  _type: 'span',
                  marks: [],
                  text: 'Vivamus lacinia odio vitae vestibulum.',
               },
            ],
         },
      ],
      preview: {
         _type: 'file',
         asset: {
            _ref: 'https://player.vimeo.com/external/269971860.hd.mp4?s=eae965838585cc8342bb5d5253d06a52b2415570&profile_id=174&oauth2_token_id=57447761',
            _type: 'reference',
         },
      },
      client: {_ref: 'client_ref_7', _type: 'reference'},
      _createdAt: new Date('2023-05-11T16:00:23.907325'),
      _updatedAt: new Date('2023-06-24T16:00:23.907328'),
      _id: 'project_2',
      _rev: 'project_rev_2',
      _type: 'project',
      category: {_ref: 'category_6', _type: 'reference'},
   },
   {
      title: 'Project Title 3',
      slug: {current: 'project-title-3', _type: 'slug'},
      thumbnail: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      releaseDate: new Date('2022-09-03T16:00:23.907335'),
      description: [
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_8319',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_4358',
                  _type: 'span',
                  marks: [],
                  text: 'Donec in efficitur leo, sed egestas tortor.',
               },
            ],
         },
      ],
      preview: {
         _type: 'file',
         asset: {
            _ref: 'https://player.vimeo.com/external/269971860.hd.mp4?s=eae965838585cc8342bb5d5253d06a52b2415570&profile_id=174&oauth2_token_id=57447761',
            _type: 'reference',
         },
      },
      client: {_ref: 'client_ref_10', _type: 'reference'},
      _createdAt: new Date('2023-07-04T16:00:23.907346'),
      _updatedAt: new Date('2023-05-18T16:00:23.907350'),
      _id: 'project_3',
      _rev: 'project_rev_3',
      _type: 'project',
      category: {_ref: 'category_5', _type: 'reference'},
   },
   {
      title: 'Project Title 4',
      slug: {current: 'project-title-4', _type: 'slug'},
      thumbnail: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      releaseDate: new Date('2023-06-15T16:00:23.907356'),
      description: [
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_7540',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_7732',
                  _type: 'span',
                  marks: [],
                  text: 'Proin sit amet mauris id libero pretium pharetra in in leo.',
               },
            ],
         },
      ],
      preview: {
         _type: 'file',
         asset: {
            _ref: 'https://player.vimeo.com/external/269971860.hd.mp4?s=eae965838585cc8342bb5d5253d06a52b2415570&profile_id=174&oauth2_token_id=57447761',
            _type: 'reference',
         },
      },
      client: {_ref: 'client_ref_3', _type: 'reference'},
      _createdAt: new Date('2022-09-18T16:00:23.907367'),
      _updatedAt: new Date('2023-07-31T16:00:23.907370'),
      _id: 'project_4',
      _rev: 'project_rev_4',
      _type: 'project',
      category: {_ref: 'category_5', _type: 'reference'},
   },
   {
      title: 'Project Title 5',
      slug: {current: 'project-title-5', _type: 'slug'},
      thumbnail: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      releaseDate: new Date('2023-05-21T16:00:23.907376'),
      description: [
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_5772',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_7530',
                  _type: 'span',
                  marks: [],
                  text: 'Donec in efficitur leo, sed egestas tortor.',
               },
            ],
         },
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_3338',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_4716',
                  _type: 'span',
                  marks: [],
                  text: 'Donec in efficitur leo, sed egestas tortor.',
               },
            ],
         },
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_1192',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_4467',
                  _type: 'span',
                  marks: [],
                  text: 'Proin sit amet mauris id libero pretium pharetra in in leo.',
               },
            ],
         },
      ],
      preview: {
         _type: 'file',
         asset: {
            _ref: 'https://player.vimeo.com/external/269971860.hd.mp4?s=eae965838585cc8342bb5d5253d06a52b2415570&profile_id=174&oauth2_token_id=57447761',
            _type: 'reference',
         },
      },
      client: {_ref: 'client_ref_10', _type: 'reference'},
      _createdAt: new Date('2023-05-12T16:00:23.907393'),
      _updatedAt: new Date('2023-06-17T16:00:23.907396'),
      _id: 'project_5',
      _rev: 'project_rev_5',
      _type: 'project',
      category: {_ref: 'category_5', _type: 'reference'},
   },
   {
      title: 'Project Title 6',
      slug: {current: 'project-title-6', _type: 'slug'},
      thumbnail: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      releaseDate: new Date('2023-05-12T16:00:23.907402'),
      description: [
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_3033',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_9913',
                  _type: 'span',
                  marks: [],
                  text: 'Cras id urna at risus tincidunt malesuada.',
               },
            ],
         },
      ],
      preview: {
         _type: 'file',
         asset: {
            _ref: 'https://player.vimeo.com/external/269971860.hd.mp4?s=eae965838585cc8342bb5d5253d06a52b2415570&profile_id=174&oauth2_token_id=57447761',
            _type: 'reference',
         },
      },
      client: {_ref: 'client_ref_2', _type: 'reference'},
      _createdAt: new Date('2023-08-04T16:00:23.907412'),
      _updatedAt: new Date('2023-07-23T16:00:23.907416'),
      _id: 'project_6',
      _rev: 'project_rev_6',
      _type: 'project',
      category: {_ref: 'category_3', _type: 'reference'},
   },
   {
      title: 'Project Title 7',
      slug: {current: 'project-title-7', _type: 'slug'},
      thumbnail: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      releaseDate: new Date('2022-12-16T16:00:23.907421'),
      description: [
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_5050',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_9530',
                  _type: 'span',
                  marks: [],
                  text: 'Donec in efficitur leo, sed egestas tortor.',
               },
            ],
         },
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_7403',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_7121',
                  _type: 'span',
                  marks: [],
                  text: 'Cras id urna at risus tincidunt malesuada.',
               },
            ],
         },
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_449',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_2116',
                  _type: 'span',
                  marks: [],
                  text: 'Proin sit amet mauris id libero pretium pharetra in in leo.',
               },
            ],
         },
      ],
      preview: {
         _type: 'file',
         asset: {
            _ref: 'https://player.vimeo.com/external/269971860.hd.mp4?s=eae965838585cc8342bb5d5253d06a52b2415570&profile_id=174&oauth2_token_id=57447761',
            _type: 'reference',
         },
      },
      client: {_ref: 'client_ref_4', _type: 'reference'},
      _createdAt: new Date('2022-08-21T16:00:23.907438'),
      _updatedAt: new Date('2023-05-24T16:00:23.907441'),
      _id: 'project_7',
      _rev: 'project_rev_7',
      _type: 'project',
      category: {_ref: 'category_2', _type: 'reference'},
   },
   {
      title: 'Project Title 8',
      slug: {current: 'project-title-8', _type: 'slug'},
      thumbnail: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      releaseDate: new Date('2023-02-04T16:00:23.907447'),
      description: [
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_7468',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_9101',
                  _type: 'span',
                  marks: [],
                  text: 'Proin sit amet mauris id libero pretium pharetra in in leo.',
               },
            ],
         },
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_5204',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_8389',
                  _type: 'span',
                  marks: [],
                  text: 'Proin sit amet mauris id libero pretium pharetra in in leo.',
               },
            ],
         },
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_9550',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_919',
                  _type: 'span',
                  marks: [],
                  text: 'Donec in efficitur leo, sed egestas tortor.',
               },
            ],
         },
      ],
      preview: {
         _type: 'file',
         asset: {
            _ref: 'https://player.vimeo.com/external/269971860.hd.mp4?s=eae965838585cc8342bb5d5253d06a52b2415570&profile_id=174&oauth2_token_id=57447761',
            _type: 'reference',
         },
      },
      client: {_ref: 'client_ref_1', _type: 'reference'},
      _createdAt: new Date('2023-04-06T16:00:23.907464'),
      _updatedAt: new Date('2023-06-04T16:00:23.907468'),
      _id: 'project_8',
      _rev: 'project_rev_8',
      _type: 'project',
      category: {_ref: 'category_1', _type: 'reference'},
   },
   {
      title: 'Project Title 9',
      slug: {current: 'project-title-9', _type: 'slug'},
      thumbnail: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      releaseDate: new Date('2023-08-19T16:00:23.907474'),
      description: [
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_6268',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_9187',
                  _type: 'span',
                  marks: [],
                  text: 'Donec in efficitur leo, sed egestas tortor.',
               },
            ],
         },
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_1096',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_8902',
                  _type: 'span',
                  marks: [],
                  text: 'Vivamus lacinia odio vitae vestibulum.',
               },
            ],
         },
      ],
      preview: {
         _type: 'file',
         asset: {
            _ref: 'https://player.vimeo.com/external/269971860.hd.mp4?s=eae965838585cc8342bb5d5253d06a52b2415570&profile_id=174&oauth2_token_id=57447761',
            _type: 'reference',
         },
      },
      client: {_ref: 'client_ref_1', _type: 'reference'},
      _createdAt: new Date('2022-12-02T16:00:23.907487'),
      _updatedAt: new Date('2023-08-09T16:00:23.907490'),
      _id: 'project_9',
      _rev: 'project_rev_9',
      _type: 'project',
      category: {_ref: 'category_4', _type: 'reference'},
   },
   {
      title: 'Project Title 10',
      slug: {current: 'project-title-10', _type: 'slug'},
      thumbnail: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      releaseDate: new Date('2023-04-08T16:00:23.907497'),
      description: [
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_4298',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_1175',
                  _type: 'span',
                  marks: [],
                  text: 'Donec in efficitur leo, sed egestas tortor.',
               },
            ],
         },
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_1206',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_5204',
                  _type: 'span',
                  marks: [],
                  text: 'Vivamus lacinia odio vitae vestibulum.',
               },
            ],
         },
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_5392',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_2045',
                  _type: 'span',
                  marks: [],
                  text: 'Vivamus lacinia odio vitae vestibulum.',
               },
            ],
         },
      ],
      preview: {
         _type: 'file',
         asset: {
            _ref: 'https://player.vimeo.com/external/269971860.hd.mp4?s=eae965838585cc8342bb5d5253d06a52b2415570&profile_id=174&oauth2_token_id=57447761',
            _type: 'reference',
         },
      },
      client: {_ref: 'client_ref_7', _type: 'reference'},
      _createdAt: new Date('2023-01-15T16:00:23.907514'),
      _updatedAt: new Date('2023-08-01T16:00:23.907517'),
      _id: 'project_10',
      _rev: 'project_rev_10',
      _type: 'project',
      category: {_ref: 'category_4', _type: 'reference'},
   },
   {
      title: 'Project Title 11',
      slug: {current: 'project-title-11', _type: 'slug'},
      thumbnail: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      releaseDate: new Date('2023-05-02T16:00:23.907523'),
      description: [
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_3249',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_4350',
                  _type: 'span',
                  marks: [],
                  text: 'Cras id urna at risus tincidunt malesuada.',
               },
            ],
         },
      ],
      preview: {
         _type: 'file',
         asset: {
            _ref: 'https://player.vimeo.com/external/269971860.hd.mp4?s=eae965838585cc8342bb5d5253d06a52b2415570&profile_id=174&oauth2_token_id=57447761',
            _type: 'reference',
         },
      },
      client: {_ref: 'client_ref_6', _type: 'reference'},
      _createdAt: new Date('2023-03-29T16:00:23.907532'),
      _updatedAt: new Date('2023-06-26T16:00:23.907536'),
      _id: 'project_11',
      _rev: 'project_rev_11',
      _type: 'project',
      category: {_ref: 'category_6', _type: 'reference'},
   },
   {
      title: 'Project Title 12',
      slug: {current: 'project-title-12', _type: 'slug'},
      thumbnail: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      releaseDate: new Date('2023-03-04T16:00:23.907541'),
      description: [
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_9208',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_2426',
                  _type: 'span',
                  marks: [],
                  text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
               },
            ],
         },
      ],
      preview: {
         _type: 'file',
         asset: {
            _ref: 'https://player.vimeo.com/external/269971860.hd.mp4?s=eae965838585cc8342bb5d5253d06a52b2415570&profile_id=174&oauth2_token_id=57447761',
            _type: 'reference',
         },
      },
      client: {_ref: 'client_ref_4', _type: 'reference'},
      _createdAt: new Date('2023-03-07T16:00:23.907551'),
      _updatedAt: new Date('2023-06-26T16:00:23.907555'),
      _id: 'project_12',
      _rev: 'project_rev_12',
      _type: 'project',
      category: {_ref: 'category_1', _type: 'reference'},
   },
   {
      title: 'Project Title 13',
      slug: {current: 'project-title-13', _type: 'slug'},
      thumbnail: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      releaseDate: new Date('2022-11-08T16:00:23.907560'),
      description: [
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_7903',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_5150',
                  _type: 'span',
                  marks: [],
                  text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
               },
            ],
         },
      ],
      preview: {
         _type: 'file',
         asset: {
            _ref: 'https://player.vimeo.com/external/269971860.hd.mp4?s=eae965838585cc8342bb5d5253d06a52b2415570&profile_id=174&oauth2_token_id=57447761',
            _type: 'reference',
         },
      },
      client: {_ref: 'client_ref_9', _type: 'reference'},
      _createdAt: new Date('2022-09-27T16:00:23.907570'),
      _updatedAt: new Date('2023-08-10T16:00:23.907574'),
      _id: 'project_13',
      _rev: 'project_rev_13',
      _type: 'project',
      category: {_ref: 'category_4', _type: 'reference'},
   },
   {
      title: 'Project Title 14',
      slug: {current: 'project-title-14', _type: 'slug'},
      thumbnail: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      releaseDate: new Date('2023-03-31T16:00:23.907706'),
      description: [
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_5618',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_6239',
                  _type: 'span',
                  marks: [],
                  text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
               },
            ],
         },
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_4387',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_7140',
                  _type: 'span',
                  marks: [],
                  text: 'Cras id urna at risus tincidunt malesuada.',
               },
            ],
         },
      ],
      preview: {
         _type: 'file',
         asset: {
            _ref: 'https://player.vimeo.com/external/269971860.hd.mp4?s=eae965838585cc8342bb5d5253d06a52b2415570&profile_id=174&oauth2_token_id=57447761',
            _type: 'reference',
         },
      },
      client: {_ref: 'client_ref_5', _type: 'reference'},
      _createdAt: new Date('2023-06-29T16:00:23.907722'),
      _updatedAt: new Date('2023-08-13T16:00:23.907725'),
      _id: 'project_14',
      _rev: 'project_rev_14',
      _type: 'project',
      category: {_ref: 'category_4', _type: 'reference'},
   },
   {
      title: 'Project Title 15',
      slug: {current: 'project-title-15', _type: 'slug'},
      thumbnail: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      releaseDate: new Date('2023-08-16T16:00:23.907731'),
      description: [
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_6610',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_465',
                  _type: 'span',
                  marks: [],
                  text: 'Donec in efficitur leo, sed egestas tortor.',
               },
            ],
         },
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_6589',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_565',
                  _type: 'span',
                  marks: [],
                  text: 'Donec in efficitur leo, sed egestas tortor.',
               },
            ],
         },
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_2768',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_4789',
                  _type: 'span',
                  marks: [],
                  text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
               },
            ],
         },
      ],
      preview: {
         _type: 'file',
         asset: {
            _ref: 'https://player.vimeo.com/external/269971860.hd.mp4?s=eae965838585cc8342bb5d5253d06a52b2415570&profile_id=174&oauth2_token_id=57447761',
            _type: 'reference',
         },
      },
      client: {_ref: 'client_ref_5', _type: 'reference'},
      _createdAt: new Date('2023-01-31T16:00:23.907754'),
      _updatedAt: new Date('2023-06-09T16:00:23.907760'),
      _id: 'project_15',
      _rev: 'project_rev_15',
      _type: 'project',
      category: {_ref: 'category_6', _type: 'reference'},
   },
   {
      title: 'Project Title 16',
      slug: {current: 'project-title-16', _type: 'slug'},
      thumbnail: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      releaseDate: new Date('2022-10-21T16:00:23.907769'),
      description: [
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_7660',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_8646',
                  _type: 'span',
                  marks: [],
                  text: 'Proin sit amet mauris id libero pretium pharetra in in leo.',
               },
            ],
         },
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_8915',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_7007',
                  _type: 'span',
                  marks: [],
                  text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
               },
            ],
         },
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_3783',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_7764',
                  _type: 'span',
                  marks: [],
                  text: 'Cras id urna at risus tincidunt malesuada.',
               },
            ],
         },
      ],
      preview: {
         _type: 'file',
         asset: {
            _ref: 'https://player.vimeo.com/external/269971860.hd.mp4?s=eae965838585cc8342bb5d5253d06a52b2415570&profile_id=174&oauth2_token_id=57447761',
            _type: 'reference',
         },
      },
      client: {_ref: 'client_ref_7', _type: 'reference'},
      _createdAt: new Date('2022-12-18T16:00:23.907795'),
      _updatedAt: new Date('2023-07-04T16:00:23.907801'),
      _id: 'project_16',
      _rev: 'project_rev_16',
      _type: 'project',
      category: {_ref: 'category_5', _type: 'reference'},
   },
   {
      title: 'Project Title 17',
      slug: {current: 'project-title-17', _type: 'slug'},
      thumbnail: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      releaseDate: new Date('2023-07-04T16:00:23.907811'),
      description: [
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_7169',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_176',
                  _type: 'span',
                  marks: [],
                  text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
               },
            ],
         },
      ],
      preview: {
         _type: 'file',
         asset: {
            _ref: 'https://player.vimeo.com/external/269971860.hd.mp4?s=eae965838585cc8342bb5d5253d06a52b2415570&profile_id=174&oauth2_token_id=57447761',
            _type: 'reference',
         },
      },
      client: {_ref: 'client_ref_1', _type: 'reference'},
      _createdAt: new Date('2022-12-07T16:00:23.907824'),
      _updatedAt: new Date('2023-07-22T16:00:23.907828'),
      _id: 'project_17',
      _rev: 'project_rev_17',
      _type: 'project',
      category: {_ref: 'category_4', _type: 'reference'},
   },
   {
      title: 'Project Title 18',
      slug: {current: 'project-title-18', _type: 'slug'},
      thumbnail: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      releaseDate: new Date('2023-04-05T16:00:23.907834'),
      description: [
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_2384',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_9969',
                  _type: 'span',
                  marks: [],
                  text: 'Proin sit amet mauris id libero pretium pharetra in in leo.',
               },
            ],
         },
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_4259',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_6022',
                  _type: 'span',
                  marks: [],
                  text: 'Cras id urna at risus tincidunt malesuada.',
               },
            ],
         },
      ],
      preview: {
         _type: 'file',
         asset: {
            _ref: 'https://player.vimeo.com/external/269971860.hd.mp4?s=eae965838585cc8342bb5d5253d06a52b2415570&profile_id=174&oauth2_token_id=57447761',
            _type: 'reference',
         },
      },
      client: {_ref: 'client_ref_2', _type: 'reference'},
      _createdAt: new Date('2023-05-27T16:00:23.908224'),
      _updatedAt: new Date('2023-06-03T16:00:23.908247'),
      _id: 'project_18',
      _rev: 'project_rev_18',
      _type: 'project',
      category: {_ref: 'category_5', _type: 'reference'},
   },
   {
      title: 'Project Title 19',
      slug: {current: 'project-title-19', _type: 'slug'},
      thumbnail: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      releaseDate: new Date('2023-08-01T16:00:23.908267'),
      description: [
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_4755',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_838',
                  _type: 'span',
                  marks: [],
                  text: 'Cras id urna at risus tincidunt malesuada.',
               },
            ],
         },
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_4005',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_5491',
                  _type: 'span',
                  marks: [],
                  text: 'Vivamus lacinia odio vitae vestibulum.',
               },
            ],
         },
      ],
      preview: {
         _type: 'file',
         asset: {
            _ref: 'https://player.vimeo.com/external/269971860.hd.mp4?s=eae965838585cc8342bb5d5253d06a52b2415570&profile_id=174&oauth2_token_id=57447761',
            _type: 'reference',
         },
      },
      client: {_ref: 'client_ref_5', _type: 'reference'},
      _createdAt: new Date('2022-10-06T16:00:23.908297'),
      _updatedAt: new Date('2023-07-12T16:00:23.908304'),
      _id: 'project_19',
      _rev: 'project_rev_19',
      _type: 'project',
      category: {_ref: 'category_3', _type: 'reference'},
   },
   {
      title: 'Project Title 20',
      slug: {current: 'project-title-20', _type: 'slug'},
      thumbnail: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      releaseDate: new Date('2023-05-31T16:00:23.908315'),
      description: [
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_2416',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_4419',
                  _type: 'span',
                  marks: [],
                  text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
               },
            ],
         },
      ],
      preview: {
         _type: 'file',
         asset: {
            _ref: 'https://player.vimeo.com/external/269971860.hd.mp4?s=eae965838585cc8342bb5d5253d06a52b2415570&profile_id=174&oauth2_token_id=57447761',
            _type: 'reference',
         },
      },
      client: {_ref: 'client_ref_5', _type: 'reference'},
      _createdAt: new Date('2023-03-20T16:00:23.908335'),
      _updatedAt: new Date('2023-06-02T16:00:23.908341'),
      _id: 'project_20',
      _rev: 'project_rev_20',
      _type: 'project',
      category: {_ref: 'category_2', _type: 'reference'},
   },
   {
      title: 'Project Title 21',
      slug: {current: 'project-title-21', _type: 'slug'},
      thumbnail: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      releaseDate: new Date('2023-04-24T16:00:23.908352'),
      description: [
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_5745',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_6363',
                  _type: 'span',
                  marks: [],
                  text: 'Donec in efficitur leo, sed egestas tortor.',
               },
            ],
         },
      ],
      preview: {
         _type: 'file',
         asset: {
            _ref: 'https://player.vimeo.com/external/269971860.hd.mp4?s=eae965838585cc8342bb5d5253d06a52b2415570&profile_id=174&oauth2_token_id=57447761',
            _type: 'reference',
         },
      },
      client: {_ref: 'client_ref_2', _type: 'reference'},
      _createdAt: new Date('2022-12-29T16:00:23.908370'),
      _updatedAt: new Date('2023-06-30T16:00:23.908377'),
      _id: 'project_21',
      _rev: 'project_rev_21',
      _type: 'project',
      category: {_ref: 'category_5', _type: 'reference'},
   },
   {
      title: 'Project Title 22',
      slug: {current: 'project-title-22', _type: 'slug'},
      thumbnail: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      releaseDate: new Date('2022-12-27T16:00:23.908387'),
      description: [
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_6139',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_9446',
                  _type: 'span',
                  marks: [],
                  text: 'Vivamus lacinia odio vitae vestibulum.',
               },
            ],
         },
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_8960',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_3862',
                  _type: 'span',
                  marks: [],
                  text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
               },
            ],
         },
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_7404',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_6875',
                  _type: 'span',
                  marks: [],
                  text: 'Proin sit amet mauris id libero pretium pharetra in in leo.',
               },
            ],
         },
      ],
      preview: {
         _type: 'file',
         asset: {
            _ref: 'https://player.vimeo.com/external/269971860.hd.mp4?s=eae965838585cc8342bb5d5253d06a52b2415570&profile_id=174&oauth2_token_id=57447761',
            _type: 'reference',
         },
      },
      client: {_ref: 'client_ref_6', _type: 'reference'},
      _createdAt: new Date('2023-02-23T16:00:23.908441'),
      _updatedAt: new Date('2023-05-15T16:00:23.908447'),
      _id: 'project_22',
      _rev: 'project_rev_22',
      _type: 'project',
      category: {_ref: 'category_2', _type: 'reference'},
   },
   {
      title: 'Project Title 23',
      slug: {current: 'project-title-23', _type: 'slug'},
      thumbnail: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      releaseDate: new Date('2023-01-19T16:00:23.908457'),
      description: [
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_2156',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_3980',
                  _type: 'span',
                  marks: [],
                  text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
               },
            ],
         },
      ],
      preview: {
         _type: 'file',
         asset: {
            _ref: 'https://player.vimeo.com/external/269971860.hd.mp4?s=eae965838585cc8342bb5d5253d06a52b2415570&profile_id=174&oauth2_token_id=57447761',
            _type: 'reference',
         },
      },
      client: {_ref: 'client_ref_4', _type: 'reference'},
      _createdAt: new Date('2022-12-27T16:00:23.908475'),
      _updatedAt: new Date('2023-08-07T16:00:23.908481'),
      _id: 'project_23',
      _rev: 'project_rev_23',
      _type: 'project',
      category: {_ref: 'category_2', _type: 'reference'},
   },
   {
      title: 'Project Title 24',
      slug: {current: 'project-title-24', _type: 'slug'},
      thumbnail: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      releaseDate: new Date('2023-01-06T16:00:23.908491'),
      description: [
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_4843',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_6762',
                  _type: 'span',
                  marks: [],
                  text: 'Proin sit amet mauris id libero pretium pharetra in in leo.',
               },
            ],
         },
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_2755',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_204',
                  _type: 'span',
                  marks: [],
                  text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
               },
            ],
         },
      ],
      preview: {
         _type: 'file',
         asset: {
            _ref: 'https://player.vimeo.com/external/269971860.hd.mp4?s=eae965838585cc8342bb5d5253d06a52b2415570&profile_id=174&oauth2_token_id=57447761',
            _type: 'reference',
         },
      },
      client: {_ref: 'client_ref_8', _type: 'reference'},
      _createdAt: new Date('2022-10-11T16:00:23.908526'),
      _updatedAt: new Date('2023-05-19T16:00:23.908533'),
      _id: 'project_24',
      _rev: 'project_rev_24',
      _type: 'project',
      category: {_ref: 'category_3', _type: 'reference'},
   },
   {
      title: 'Project Title 25',
      slug: {current: 'project-title-25', _type: 'slug'},
      thumbnail: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      releaseDate: new Date('2023-01-27T16:00:23.908543'),
      description: [
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_2381',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_818',
                  _type: 'span',
                  marks: [],
                  text: 'Cras id urna at risus tincidunt malesuada.',
               },
            ],
         },
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_9208',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_2285',
                  _type: 'span',
                  marks: [],
                  text: 'Proin sit amet mauris id libero pretium pharetra in in leo.',
               },
            ],
         },
         {
            _type: 'block',
            style: 'normal',
            _key: 'desc_key_9768',
            markDefs: [],
            children: [
               {
                  _key: 'child_key_6918',
                  _type: 'span',
                  marks: [],
                  text: 'Vivamus lacinia odio vitae vestibulum.',
               },
            ],
         },
      ],
      preview: {
         _type: 'file',
         asset: {
            _ref: 'https://player.vimeo.com/external/269971860.hd.mp4?s=eae965838585cc8342bb5d5253d06a52b2415570&profile_id=174&oauth2_token_id=57447761',
            _type: 'reference',
         },
      },
      client: {_ref: 'client_ref_2', _type: 'reference'},
      _createdAt: new Date('2022-09-04T16:00:23.908572'),
      _updatedAt: new Date('2023-06-09T16:00:23.908579'),
      _id: 'project_25',
      _rev: 'project_rev_25',
      _type: 'project',
      category: {_ref: 'category_5', _type: 'reference'},
   },
]

export const mockedBrands = [
   {
      name: 'Brand 1',
      slug: {_type: 'slug', current: 'brand-1'},
      image: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      _createdAt: new Date('2023-06-25T16:16:46.495061'),
      _updatedAt: new Date('2023-07-12T16:16:46.495083'),
      _id: 'brand_1',
      _rev: 'brand_rev_1',
      _type: 'brand',
   },
   {
      name: 'Brand 2',
      slug: {_type: 'slug', current: 'brand-2'},
      image: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      _createdAt: new Date('2022-09-25T16:16:46.495091'),
      _updatedAt: new Date('2023-05-30T16:16:46.495096'),
      _id: 'brand_2',
      _rev: 'brand_rev_2',
      _type: 'brand',
   },
   {
      name: 'Brand 3',
      slug: {_type: 'slug', current: 'brand-3'},
      image: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      _createdAt: new Date('2023-03-31T16:16:46.495102'),
      _updatedAt: new Date('2023-07-29T16:16:46.495105'),
      _id: 'brand_3',
      _rev: 'brand_rev_3',
      _type: 'brand',
   },
   {
      name: 'Brand 4',
      slug: {_type: 'slug', current: 'brand-4'},
      image: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      _createdAt: new Date('2022-10-21T16:16:46.495111'),
      _updatedAt: new Date('2023-07-23T16:16:46.495115'),
      _id: 'brand_4',
      _rev: 'brand_rev_4',
      _type: 'brand',
   },
   {
      name: 'Brand 5',
      slug: {_type: 'slug', current: 'brand-5'},
      image: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      _createdAt: new Date('2022-11-28T16:16:46.495120'),
      _updatedAt: new Date('2023-07-05T16:16:46.495124'),
      _id: 'brand_5',
      _rev: 'brand_rev_5',
      _type: 'brand',
   },
   {
      name: 'Brand 6',
      slug: {_type: 'slug', current: 'brand-6'},
      image: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      _createdAt: new Date('2023-03-07T16:16:46.495129'),
      _updatedAt: new Date('2023-08-20T16:16:46.495133'),
      _id: 'brand_6',
      _rev: 'brand_rev_6',
      _type: 'brand',
   },
   {
      name: 'Brand 7',
      slug: {_type: 'slug', current: 'brand-7'},
      image: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      _createdAt: new Date('2023-03-13T16:16:46.495137'),
      _updatedAt: new Date('2023-07-22T16:16:46.495141'),
      _id: 'brand_7',
      _rev: 'brand_rev_7',
      _type: 'brand',
   },
   {
      name: 'Brand 8',
      slug: {_type: 'slug', current: 'brand-8'},
      image: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      _createdAt: new Date('2022-12-06T16:16:46.495146'),
      _updatedAt: new Date('2023-07-15T16:16:46.495150'),
      _id: 'brand_8',
      _rev: 'brand_rev_8',
      _type: 'brand',
   },
   {
      name: 'Brand 9',
      slug: {_type: 'slug', current: 'brand-9'},
      image: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      _createdAt: new Date('2022-09-28T16:16:46.495154'),
      _updatedAt: new Date('2023-07-30T16:16:46.495158'),
      _id: 'brand_9',
      _rev: 'brand_rev_9',
      _type: 'brand',
   },
   {
      name: 'Brand 10',
      slug: {_type: 'slug', current: 'brand-10'},
      image: {_type: 'image', asset: {_ref: '/imaheholder-mid.jpg', _type: 'reference'}},
      _createdAt: new Date('2022-12-26T16:16:46.495163'),
      _updatedAt: new Date('2023-05-14T16:16:46.495166'),
      _id: 'brand_10',
      _rev: 'brand_rev_10',
      _type: 'brand',
   },
]
